### PR TITLE
issue #51: set up Maven multi-module project

### PR DESCRIPTION
**Pull request by luuuis**
this will allow compiling and releasing with one command from the
top-level directory.

* changed version to 2.0.0-SNAPSHOT as per Maven convention
* moved common settings into top-level pom.xml
* tweaked artifactId's to match the directory name
* use enforcer plugin to ensure we use the right JDK and Maven versions

### CODE REVIEW

**Comment by pitbulk** [comment]
Made the change [here](https://github.com/onelogin/java-saml/commit/9b6015c6bc0ece2958dd286f98ea48fb1ff871f8) (I want to keep the java-saml name) , but there are 2 test that fails (related with date/times):
* [testParseDuration](https://github.com/onelogin/java-saml/blob/v2.0.0/core/src/test/java/com/onelogin/saml2/test/util/UtilsTest.java#L1972)
- [testGetCurrentTimeStamp](https://github.com/onelogin/java-saml/blob/v2.0.0/core/src/test/java/com/onelogin/saml2/test/util/UtilsTest.java#L1992)

@luuuis does the test also fail in your local?

**Comment by luuuis** [comment]
Sorry about the missing dependency, I forgot to update the name in the jspsample pom as well.

I did have a single failure in `testParseDuration` @pitbulk but I ignored it since it was already failing before my changes (see [build #2](https://travis-ci.org/onelogin/java-saml/jobs/150792587)).

**Comment by pitbulk** [comment]
Yes, I know is a previous issue. Do you experience it as well in your local?

**Comment by luuuis** [comment]
Yes, I get the failure locally. I just debugged it and the test assertion itself is incorrect as shown by this screenshot.

image

As you can see the expected date/time is off by 1 hour (the hour should be unchanged when adding P1Y1M). It could be that the original calculation did not take daylight saving into account? I think we can simply change the expected timestamp to `1428091225L`.

**Comment by pitbulk** [comment]
On my local works, so it should work on both machines :)

Maybe is related to the machine local time, but I thought I did the methods independent. I will need to review the duration method. A couple of extra eyes welcome :)

**Comment by luuuis** [comment]
What is your timezone as output by `System.out.println(TimeZone.getDefault());`?

**Comment by pitbulk** [comment]
Im not right now with my laptop, I will reply in a couple of hours

**Comment by luuuis** [comment]
Ok, guessing that your timezone is `Europe/Madrid` I was able to successfully run the test by passing `-Duser.timezone=Europe/Madrid`. The problem is that a `org.joda.time.Period` is relative to a date, time, and time zone so all "period arithmetic" will take the time zone into account. 

Examples:
* if you are about to enter DST in 1 minute then a period of `PT1H` is equal to a duration of 3600 seconds
* the number of days in P1M is different depending on whether it's February or another month

Solutions:
* `testParseDuration()` can be changed to use a specific time zone
* `Utils.parseDuration()` can be changed to only accept time-based durations (e.g. `PT*H*M*S`) which are less susceptible to this problem (although you can still have leap seconds)

What does SAML have to say about how the duration should be interpreted in these cases?

**Comment by pitbulk** [comment]
Dates in SAML should be always consider as UTC

**Comment by pitbulk** [comment]
Ok fixed the issue with the time, now the Travis is ok. We can continue wth the rest of tasks.

**Pull request merged**
