### PR TITLE
WIP : Feature - Support KeyStore for SP Certificate and Key

### PR DESCRIPTION
**Pull request by ProcrastinatorCp**
### Changes in this PR : 
- New **Auth()** methods which supports `KeyStore` initialization of settings. 
- Support **JKS** KeyStore type. 
- Tests
- Seems few auto-format of java-doc by **eclipse**. (Please let me know if not OK)

### CODE REVIEW

**Comment by pitbulk** [comment]
Code looks good. I will need some days to test it myself and merge.

Thanks for your contribution!

**Comment by ProcrastinatorCp** [comment]
Added a new commit which  :   
- new class for KeyStore settings : `KeyStoreSettings`  
  - In future, it can be modified to include other cert/key. (like : sp_future_cert)
- adds  option for loading dynamic setting.  
`public SettingsBuilder fromValues(Map<String, Object> samlData, KeyStoreSettings keyStoreSetting)` 

Once it's good to go, I will update **README** for related changes.

**Comment by ProcrastinatorCp** [comment]
@pitbulk Sorry to bother you. Did you get a change to review the PR.

**Comment by pitbulk** [comment]
Sorry for the delay, I will have some time tomorrow

**Pull request merged**
