### PR TITLE
Adjusted the core library, toolkit and the sample application to supp…

### PR DESCRIPTION
**Pull request by median1st**
…ort logout from Shibboleth IdP3.

**This is a pull request in response to comments in issue #169** .

Changes made:
	- added NameID.java to com.onelogin.saml2.authn
	- adjusted LogoutRequest to use NameID instances and generate corresponding NameId XML element
	- adjusted Util.java to work with NameID
	- adjusted acs.jsp to extract NameID from login response
	- adjusted dologout.jsp to supply NameId and SessionIndex to Auth
	- added a logout() method to Auth.java that accepts a NameID as argument
	- adjusted LogoutRequestTest.java and AuthTest.java to work with the original methods (typecasts to resolve ambigous references)

### CODE REVIEW

**Comment by pitbulk** [comment]
Thanks for providing the PR, I will review it carefully and merge it or a solution inspired by that PR.

**Comment by pitbulk** [comment]
Sorry for the delay. I hope to have time next week and review & merge that PR.

**Comment by AyWa** [comment]
No problem :)
Btw I tested and it is working well. 

About the implementation, I am not sure if it is good or not to have a NameId class (I dont have much background about this library so I guess others will know better) but if it is, It could be good if the class was Serializable. 
Let me know if I can help on something :)

**Comment by AyWa** [comment]
@pitbulk 

Sorry to come back to you. Did you have any update on it ?

I am willing to help you if you need.

**Comment by pitbulk** [comment]
See https://github.com/onelogin/java-saml/commit/ba141697df4bb1cd670c61307e1de7767670bf8c

**Pull request closed without merging**
