### PR TITLE
Be able to handle multiple signing certs provided by AzureAD IdP

### PR DESCRIPTION
**Pull request by anderson-sillos**
Allow to set multiple fingerprints comma separated in `onelogin.saml2.idp.certfingerprint` config parameter.

### CODE REVIEW

**Comment by anderson-sillos** [comment]
@pitbulk & @miszobi, it takes something else for this approach to be merged? Or would not this viable? Thanks

**Comment by pitbulk** [comment]
Rather than support just fingerprints the desired solution will be to support multiple certs for sign and encrypt as implemented [here](https://github.com/onelogin/php-saml/commit/84aa522b27a8d44cfc2f0229aa8963b9de438eec). But had no time to implement it on java-saml yet.

**Comment by anderson-sillos** [comment]
thanks @pitbulk, then I´ll provide the solution you described, OK?

**Comment by anderson-sillos** [comment]
Hi @pitbulk, could you review this implementation?

**Comment by pitbulk** [comment]
The implementation seems to work, but I see you only covered
onelogin.saml2.idp.x509certMulti for signing.

Maybe we can extend it and use:
onelogin.saml2.idp.x509certMulti.signing.0 =
onelogin.saml2.idp.x509certMulti.signing.1 =
onelogin.saml2.idp.x509certMulti.signing.2 =

and
onelogin.saml2.idp.x509certMulti.encryption =

Or in the documentation explain that onelogin.saml2.idp.x509certMulti covers only certs for validate signature, if admin want to set a different value for encrypt, should be placed on the onelogin.saml2.idp.x509cert parameter.

**Comment by anderson-sillos** [comment]
Yes, because always will be used just one certificate for encrypting, so it was maintained the original x509cert for this. And for signing validation will be used both x509cert and x509certMulti.

I fixed the documentation.

**Comment by pitbulk** [comment]
Thanks for this distribution, I plan to implement an IdPMetadataParser like the [one implemented on php-saml](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/IdPMetadataParser.php) and then release a new version of java-saml.

Best regards.

**Comment by anderson-sillos** [comment]
@pitbulk, how could I help you?

**Comment by pitbulk** [comment]
Basically the work to be done is to translate PHP code of the metadata parser in Java and adapt the IdP info injection, so will be able to inject into the settings builder

**Comment by anderson-sillos** [comment]
OK, I'll work on this and send a PR

**Comment by pitbulk** [comment]
great!

**Comment by pitbulk** [comment]
I created #140, @anderson-sillos please review it.

**Pull request merged**
